//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfume.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarOrder
    {
        public int IDTovarOrder { get; set; }
        public int IDTovar { get; set; }
        public int IDOrder { get; set; }
        public int Count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
