//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfume.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.TovarOrder = new HashSet<TovarOrder>();
        }
    
        public int IDTovar { get; set; }
        public string Articule { get; set; }
        public int IDName { get; set; }
        public int IDUnit { get; set; }
        public decimal Price { get; set; }
        public int IDManufacture { get; set; }
        public int IDProvider { get; set; }
        public int IDCategory { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual NameTovar NameTovar { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarOrder> TovarOrder { get; set; }

        public virtual string PhotoCurrent
        {
            get
            {
                string photo = string.IsNullOrEmpty(Photo) ? "picture.png" : Photo; 
                return "/image/" + photo;
            }
        }
    }
}
